### ISSUE TITLE
Only double mouse click should not be interpreted as buttondown or up

### ISSUE THREAD

**Issue by mattrei** [DougReeder/aframe-button-controls#2]
Hi,

I'd like to use your component however I am not happy how the mouse is interpreted. I don't think a single mouse click shall fire an event? Just by looking through the scene (pointer lock disabled) I always get button down events. How could I differente then, if an object is clicked (=action triggered) or just by looking around? I think this component should differentiate between pointer lock enabled and disabled. If disabled then just double clicks shall trigger an action.

Thx for your suggestions!

**Comment by DougReeder** [comment]
I don’t have an example where pointer lock is enabled. Do you have one?

> On Feb 6, 2019, at 10:41 AM, Matthias Treitler <notifications@github.com> wrote:
> 
> Hi,
> 
> I'd like to use your component however I am not happy how the mouse is interpreted. I don't think a single mouse click shall fire an event? Just by looking through the scene (pointer lock disabled) I always get button down events. How could I differente then, if an object is clicked (=action triggered) or just by looking around? I think this component should differentiate between pointer lock enabled and disabled. If disabled then just double clicks shall trigger an action.
> 
> Thx for your suggestions!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Doug Reeder
reeder.29@gmail.com
Recall your notes by context, with Serene Notes: https://serenenotes.hominidsoftware.com/
My gender pronouns are: he, him, his.

**Comment by mattrei** [comment]
it's just setting the [pointerLockEnabled](https://aframe.io/docs/master/components/look-controls.html#properties_pointerlockenabled) on the _look-controls_ component on a simple hello world example.

I can make a PR if you want, however it only makes sense if you are happy with my proposal above. 

also when registering double clicks with the mouse, how can we differentiate between buttondown and buttonup events? if think we should not then and just fire buttondown events. what do you think?

**Comment by DougReeder** [comment]
I'm still not clear on what the issue is, our your proposed solution.
Examples would really help!

**Comment by mattrei** [comment]
See this exampel here 
https://aframe-button-controls-issue.glitch.me/

When you open the console you see when you look around with the mouse, everytime a button down and up event is raised. This is semantically very problematic because IMO it should only fire on a real action (like clicking on an object).

When you look at the source of the above example, you see the _pointLockEnabled_ property on the _look-controls_ component, that is set to false on this example. When set to true of course there will be no issue, because I do not need to click with my mouse to look around.

Hope things are clear now! thx

**Comment by mattrei** [comment]
i am going to create a PR tomorrow, so that things get clear

**Comment by DougReeder** [comment]
I get the error “Project not found” for https://aframe-button-controls-issue.glitch.me/


> On Feb 19, 2019, at 10:10 AM, Matthias Treitler <notifications@github.com> wrote:
> 
> See this exampel here
> https://aframe-button-controls-issue.glitch.me/
> 
> When you open the console you see when you look around with the mouse, everytime a button down and up event is raised. This is semantically very problematic because IMO it should only fire on a real action (like clicking on an object).
> 
> When you look at the source of the above example, you see the pointLockEnabled property on the look-controls component, that is set to false on this example. When set to true of course there will be no issue, because I do not need to click with my mouse to look around.
> 
> Hope things are clear now! thx
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Doug Reeder
reeder.29@gmail.com
Recall your notes by context, with Serene Notes: https://serenenotes.hominidsoftware.com/
My gender pronouns are: he, him, his.

**Comment by kylebakerio** [comment]
(I can only guess that this guy had the fuse mouse enabled and that was his problem.)
